import type { Metadata } from "next";
import { Grenze, Cinzel_Decorative, Montserrat_Alternates } from "next/font/google";
import "./globals.css";

const grenze = Grenze({
  weight: "700",
  subsets: ['latin'],
  display: "swap"
})

const cinzelDecorative = Cinzel_Decorative({
  weight: "700",
  subsets: ["latin"],
  display: "swap"
})

const montserratAlternates = Montserrat_Alternates({
  weight: "500",
  subsets: ["latin"],
  display: "swap"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${montserratAlternates.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
